"""schema initial V1

Revision ID: 4449d05f663e
Revises: 
Create Date: 2026-07-01 23:45:21.338860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4449d05f663e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_profile',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_import_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('optional_skills', sa.JSON(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof',
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidentiality', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_variant',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_title', sa.String(length=300), nullable=False),
    sa.Column('recommended_summary', sa.Text(), nullable=False),
    sa.Column('adapted_text', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_variant_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cv_variant_profile_id'), ['profile_id'], unique=False)

    op.create_table('fact',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_profile_id'), ['profile_id'], unique=False)

    op.create_table('application',
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['cv_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_variant_id'), ['variant_id'], unique=False)

    op.create_table('generated_sentence',
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_fact_ids', sa.JSON(), nullable=False),
    sa.Column('source_proof_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['cv_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_sentence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_sentence_variant_id'), ['variant_id'], unique=False)

    op.create_table('proof_fact',
    sa.Column('proof_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.ForeignKeyConstraint(['proof_id'], ['proof.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proof_id', 'fact_id', name='uq_proof_fact')
    )
    with op.batch_alter_table('proof_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proof_fact_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proof_fact_proof_id'), ['proof_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proof_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proof_fact_proof_id'))
        batch_op.drop_index(batch_op.f('ix_proof_fact_fact_id'))

    op.drop_table('proof_fact')
    with op.batch_alter_table('generated_sentence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_sentence_variant_id'))

    op.drop_table('generated_sentence')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_variant_id'))
        batch_op.drop_index(batch_op.f('ix_application_offer_id'))

    op.drop_table('application')
    with op.batch_alter_table('fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_profile_id'))

    op.drop_table('fact')
    with op.batch_alter_table('cv_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_variant_profile_id'))
        batch_op.drop_index(batch_op.f('ix_cv_variant_offer_id'))

    op.drop_table('cv_variant')
    op.drop_table('proof')
    op.drop_table('offer')
    op.drop_table('master_profile')
    # ### end Alembic commands ###
